# Generated by Django 2.2.8 on 2020-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
