# Generated by Django 2.2.8 on 2020-08-19 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.FloatField(),
        ),
    ]
