# Generated by Django 2.2.8 on 2020-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fashion'), (2, 'Toys'), (3, 'Electronics'), (4, 'Home'), (5, 'Others')], default=5),
        ),
    ]
