# Generated by Django 2.2.8 on 2020-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200822_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='null', upload_to='static/auctions'),
        ),
    ]
