# Generated by Django 2.2.8 on 2020-08-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200824_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(null=True, upload_to='auctions/'),
        ),
    ]
